name: QoshKel
description: "An Online City Travel Planning Platform with AR integration and automated budget-based route generation"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#---------------PACKAGES--------------#

dependencies:
  flutter:
    sdk: flutter
  #utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^5.0.1

  #icons  
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  location: ^6.0.1
  metaballs: ^1.4.2

  #firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  # fluttertoast: ^8.2.12
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  google_sign_in: ^6.3.0
  confetti: ^0.8.0
  cached_network_image: ^3.4.0


  #Product Specific

  #----------------------./ PACKAGES END -----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS -----------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/marker/
    - assets/videos/
    - assets/images/user/
  
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/Logo Black.png
  image_dark: assets/logos/Logo White.png

  android_12:
   color: "#FFFFFF"
   color_dark: "#272727"
   image: assets/logos/Logo Black.png
   image_dark: assets/logos/Logo White.png

  web: false
