// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALs45e2SCR2vJliflK2MQtbh1j8QHzn5E',
    appId: '1:1059985057927:web:bdf4ad303ddd8f3a3a7022',
    messagingSenderId: '1059985057927',
    projectId: 'ndip-aa43b',
    authDomain: 'ndip-aa43b.firebaseapp.com',
    storageBucket: 'ndip-aa43b.firebasestorage.app',
    measurementId: 'G-RD1QC5WYX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8tpjehtYp8qNi4LWM0rIyKMhAQchpRdk',
    appId: '1:1059985057927:android:fe96ae3da07c22ee3a7022',
    messagingSenderId: '1059985057927',
    projectId: 'ndip-aa43b',
    storageBucket: 'ndip-aa43b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvTabfWxusDGK6OhYbu2ke8AzH0X14Z4',
    appId: '1:1059985057927:ios:786184650e2db31b3a7022',
    messagingSenderId: '1059985057927',
    projectId: 'ndip-aa43b',
    storageBucket: 'ndip-aa43b.firebasestorage.app',
    androidClientId: '1059985057927-scna7j3ahnic2umpgs9ijpknr70isns0.apps.googleusercontent.com',
    iosClientId: '1059985057927-0qk1369lqi77sfoprm9hf3t442sd2u71.apps.googleusercontent.com',
    iosBundleId: 'com.example.diploma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTvTabfWxusDGK6OhYbu2ke8AzH0X14Z4',
    appId: '1:1059985057927:ios:786184650e2db31b3a7022',
    messagingSenderId: '1059985057927',
    projectId: 'ndip-aa43b',
    storageBucket: 'ndip-aa43b.firebasestorage.app',
    androidClientId: '1059985057927-scna7j3ahnic2umpgs9ijpknr70isns0.apps.googleusercontent.com',
    iosClientId: '1059985057927-0qk1369lqi77sfoprm9hf3t442sd2u71.apps.googleusercontent.com',
    iosBundleId: 'com.example.diploma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALs45e2SCR2vJliflK2MQtbh1j8QHzn5E',
    appId: '1:1059985057927:web:5bf5a9522e6ad3803a7022',
    messagingSenderId: '1059985057927',
    projectId: 'ndip-aa43b',
    authDomain: 'ndip-aa43b.firebaseapp.com',
    storageBucket: 'ndip-aa43b.firebasestorage.app',
    measurementId: 'G-9CN1Y8CNNJ',
  );

}